
networks:
    task_tracker:

services:
  app-task_tracker:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
        - traefik.enable=true
        - traefik.http.routers.app-admin.rule=Host(`admin.lookin-soft.local`)
        - traefik.http.services.app-admin.loadbalancer.server.port=8000
    depends_on:
      - php
      - mysql
    networks:
      - task_tracker
    extra_hosts:
        - "host.docker.internal:host-gateway"

  mysql:
    image: mariadb:10.6.16
    restart: unless-stopped
    tty: true
    ports:
      - "3319:3306"
    environment:
      MYSQL_DATABASE: task_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    networks:
      - task_tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
    ports:
      - "8889:80"
    networks:
      - task_tracker

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - task_tracker
    extra_hosts:
        - "host.docker.internal:host-gateway"

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php

  artisan:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - task_tracker

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    environment:
      - REDIS_PORT=6379
    networks:
      - task_tracker

  mailhog:
    image: mailhog/mailhog
    restart: "no"
    ports:
      - "1025:1025"
      - "8021:8025"
    networks:
      - task_tracker

#Volumes
volumes:
  dbdata:
    driver: local
  cache:
    driver: local
